name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/Contract Tests.json" -e "25749314-da60aaac-f43c-4ae1-ac4a-f0af7b34e39e" --integration-id "142892-${{ github.run_id }}"
          postman collection run "${{ github.workspace }}/postman/collections/Documentation.json" -e "25749314-da60aaac-f43c-4ae1-ac4a-f0af7b34e39e" --integration-id "142892-${{ github.run_id }}"
          postman collection run "${{ github.workspace }}/postman/collections/Functional Tests.json" -e "25749314-da60aaac-f43c-4ae1-ac4a-f0af7b34e39e" --integration-id "142892-${{ github.run_id }}"
          postman collection run "${{ github.workspace }}/postman/collections/Security Tests.json" -e "25749314-da60aaac-f43c-4ae1-ac4a-f0af7b34e39e" --integration-id "142892-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint 0da12f32-f1b5-4e7e-b5bf-956928e6e75b --integration-id 142892
